        - containerPort: 10700
          name: wyoming
        resources:
          limits:
            memory: 256Mi
            cpu: "0.5"
          requests:
            memory: 64Mi
            cpu: "0.05"
        volumeMounts:
