apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ril-presenze-data-pvc
  namespace: http
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
