apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  N8N_PROTOCOL: https
  N8N_PORT: "5678"
  N8N_HOST: "n8n.nicolatomassoni.it"
  WEBHOOK_URL: "https://n8n.nicolatomassoni.it"
  DB_TYPE: "sqlite"