apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: personal-website-runner
  namespace: http
spec:
  replicas: 1
  template:
    spec:
      repository: nonzod/personal-website
      labels:
        - self-hosted
      dnsConfig:
        options:
          - name: ndots
            value: "1"