apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-homeassistant
  namespace: domotica
  labels:
    app: samba-homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba-homeassistant
  template:
    metadata:
      labels:
        app: samba-homeassistant
    spec:
      containers:
      - name: samba
        image: elswork/samba:latest
        ports:
        - containerPort: 139
          name: netbios
        - containerPort: 445
          name: cifs
        envFrom:
        - configMapRef:
            name: samba-config
        env:
        - name: SAMBA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: samba-credentials
              key: password
        command:
        - /bin/sh
        - -c
        - |
          /entrypoint.sh \
            -u "1000:1000:homeassistant:homeassistant:${SAMBA_PASSWORD}" \
            -s "ha-config:/shared/ha-config:rw:homeassistant"
        resources:
          limits:
            memory: 256Mi
            cpu: "0.2"
          requests:
            memory: 128Mi
            cpu: "0.1"
        volumeMounts:
        - name: ha-config-data
          mountPath: /shared/ha-config

      volumes:
      - name: ha-config-data
        hostPath:
          path: /mnt/storage
          type: Directory