apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: db
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
# LoadBalancer per connessioni dirette
apiVersion: v1
kind: Service
metadata:  
  name: postgres-lb
  namespace: db
spec:
  type: LoadBalancer
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres