apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dayz-server-pvc
  namespace: dayz
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi