apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cheshire-cat-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi # Contiene file JSON/DB piccoli
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cheshire-cat-plugins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi # I plugin possono includere dipendenze pesanti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cheshire-cat-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi