apiVersion: v1
kind: Service
metadata:
  name: shopify-proxy-service
  namespace: http
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 32774
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: shopify-proxy-service
  namespace: http
subsets:
  - addresses:
      - ip: 192.168.178.100
    ports:
      - port: 32774
