apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:nonzod/kokko.git
    path: k8s/base/ai
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
