---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicolatomassoni-website
  labels:
    app: nicolatomassoni-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nicolatomassoni-website
  template:
    metadata:
      labels:
        app: nicolatomassoni-website
    spec:
      containers:
      - name: hugo
        image: nonzod/nicolatomassoni-website:0.0.5-arm64v8
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10