---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicolatomassoni-website
  namespace: http
  labels:
    app: nicolatomassoni-website
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nicolatomassoni-website
  template:
    metadata:
      labels:
        app: nicolatomassoni-website
    spec:
      containers:
      - name: hugo
        image: ghcr.io/nonzod/personal-website:a0ab8f86fae759cd07d543b871da53032bb60548
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.05"
          limits:
            memory: "128Mi"
            cpu: "0.2"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10