apiVersion: v1
kind: Service
metadata:
  name: esphome-web
spec:
  selector:
    app: esphome
  type: ClusterIP
  ports:
  - port: 6052
    targetPort: 6052
---
apiVersion: v1
kind: Service
metadata:
  name: esphome-web-local
spec:
  selector:
    app: esphome
  type: LoadBalancer
  ports:
  - port: 6052
    targetPort: 6052