apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-piper
spec:
  selector:
    matchLabels:
      app: wyoming-piper
  template:
    metadata:
      labels:
        app: wyoming-piper
    spec:
      initContainers:
      - name: download-voice
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          cd /data
          if [ ! -f "it-IT-leonardo-medium.onnx" ]; then
            wget -O it-IT-leonardo-medium.onnx https://huggingface.co/kirys79/piper_italiano/resolve/main/Leonardo/it-IT-leonardo-medium.onnx
            wget -O it-IT-leonardo-medium.onnx.json https://huggingface.co/kirys79/piper_italiano/resolve/main/Leonardo/it-IT-leonardo-medium.onnx.json
          fi
        volumeMounts:
        - name: piper-data
          mountPath: /data
      containers:
      - name: wyoming-piper
        image: rhasspy/wyoming-piper:latest
        imagePullPolicy: Always
        args:
          - "--voice"
          - "/data/it-IT-leonardo-medium.onnx"
        ports:
        - containerPort: 10200
          name: wyoming
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.2"
        volumeMounts:
        - name: piper-data
          mountPath: /data
      volumes:
      - name: piper-data
        persistentVolumeClaim:
          claimName: piper-data-pvc
