apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-whisper
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: stt-whisper
  template:
    metadata:
      labels:
        app: stt-whisper
    spec:
      containers:
      - name: stt-whisper
        image: rhasspy/wyoming-whisper:latest
        imagePullPolicy: Always
        args:
          - "--model"
          - "tiny-int8"
          - "--language"
          - "it"
          - "--data-dir"
          - "/data"
        ports:
        - containerPort: 10300
          name: wyoming
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.1"
        volumeMounts:
        - name: whisper-data
          mountPath: /data
      volumes:
      - name: whisper-data
        persistentVolumeClaim:
          claimName: stt-whisper-data-pvc