apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-whisper
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: stt-whisper
  template:
    metadata:
      labels:
        app: stt-whisper
    spec:
      containers:
      - name: stt-whisper
        image: rhasspy/wyoming-whisper:latest
        imagePullPolicy: Always
        command:
          - "sh"
          - "-c"
        args:
          - |
            echo "Upgrading wyoming-faster-whisper with --break-system-packages..."
            pip install --upgrade --break-system-packages wyoming-faster-whisper
            echo "Starting wyoming-faster-whisper..."
            exec python3 -m wyoming_faster_whisper \
              --uri tcp://0.0.0.0:10300 \
              --model base-int8 \
              --language it \
              --data-dir /data
        ports:
        - containerPort: 10300
          name: wyoming
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.1"
        volumeMounts:
        - name: whisper-data
          mountPath: /data
      volumes:
      - name: whisper-data
        persistentVolumeClaim:
          claimName: stt-whisper-data-pvc