apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-voice-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linux-voice-assistant
  template:
    metadata:
      labels:
        app: linux-voice-assistant
    spec:
      containers:
      - name: linux-voice-assistant
        image: nonzod/linux-voice-assistant:latest
        imagePullPolicy: Always
        args:
          - "--name"
          - "linux-voice-assistant"
          - "--debug"
          - "--audio-input-device"
          - "USB PnP Sound Device Mono (echo cancelled with HDA Intel PCH Analog Stereo)"
          - "--audio-output-device"
          - "pulse/alsa_output.1.analog-stereo.echo-cancel"
        # This application needs access to the host's sound devices.
        # This requires running the container in privileged mode, which has security implications.
        securityContext:
          privileged: true
        volumeMounts:
        - name: snd
          mountPath: /dev/snd
        resources:
          limits:
            memory: 1024Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "0.05"
      volumes:
      - name: snd
        hostPath:
          path: /dev/snd
