apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-piper
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tts-piper
  template:
    metadata:
      labels:
        app: tts-piper
    spec:
      initContainers:
      - name: download-voice
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          cd /data
          if [ ! -f "leonardo-epoch=2024-step=996300.onnx" ]; then
            wget -O leonardo-epoch=2024-step=996300.onnx https://huggingface.co/kirys79/piper_italiano/resolve/main/Leonardo/leonardo-epoch=2024-step=996300.onnx
            wget -O leonardo-epoch=2024-step=996300.onnx.json https://huggingface.co/kirys79/piper_italiano/resolve/main/Leonardo/leonardo-epoch=2024-step=996300.json
          fi
        volumeMounts:
        - name: piper-data
          mountPath: /data
      containers:
      - name: tts-piper
        image: rhasspy/wyoming-piper:latest
        imagePullPolicy: Always
        args:
          - "--voice"
          - "/data/leonardo-epoch=2024-step=996300.onnx"
        ports:
        - containerPort: 10200
          name: wyoming
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.2"
        volumeMounts:
        - name: piper-data
          mountPath: /data
      volumes:
      - name: piper-data
        persistentVolumeClaim:
          claimName: piper-data-pvc
