apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: domotica

resources:
- namespace.yaml
- homeassistant
- esphome
- samba
- mpd-server
- rtsp-server
- wyoming-piper
- stt-whisper
- stt-openwakeword
- stt-satellite