apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-openwakeword
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: stt-openwakeword
  template:
    metadata:
      labels:
        app: stt-openwakeword
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ["sh", "-c", "chmod -R 777 /data"]
        volumeMounts:
        - name: openwakeword-data
          mountPath: /data
      containers:
      - name: stt-openwakeword
        image: rhasspy/wyoming-openwakeword:latest
        imagePullPolicy: Always
        args:
          - "--preload-model"
          - "ok_nabu"
          - "--custom-model-dir"
          - "/data"
          - "--debug"
        ports:
        - containerPort: 10400
          name: wyoming
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 128Mi
            cpu: "0.05"
        volumeMounts:
        - name: openwakeword-data
          mountPath: /data
      volumes:
      - name: openwakeword-data
        persistentVolumeClaim:
          claimName: stt-openwakeword-data-pvc