            cpu: "0.5"
          requests:
            memory: 128Mi
            cpu: "0.05"
        volumeMounts:
        - name: openwakeword-data
          mountPath: /data
      volumes:
      - name: openwakeword-data
        persistentVolumeClaim:
