apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  namespace: pihole
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-office"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pihole.nicolatomassoni.it
      secretName: pihole-tls
  rules:
  - host: "pihole.nicolatomassoni.it"
    http:
      paths:
      - pathType: Prefix
        path:  /
        backend:
          service:
            name: pihole-web
            port:
              number: 8000