apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-office"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - casa.nicolatomassoni.it
      secretName: homeassistant-tls
  rules:
  - host: "casa.nicolatomassoni.it"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/pihole(.+)"
        backend:
          service:
            name: pihole-web
            port:
              number: 8000