name: Secret Scanning

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  scan:
    name: gitleaks
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessario per scansionare tutto lo storico

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: true  # Commenta sulla PR se trova secrets
